"""01_init_db

Revision ID: b27e5d606663
Revises: 
Create Date: 2023-07-25 08:06:04.288341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27e5d606663'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    schema='file_app'
    )
    op.create_table('file',
    sa.Column('id_file', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_downloadable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['file_app.user.id_user'], ),
    sa.PrimaryKeyConstraint('id_file'),
    schema='file_app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file', schema='file_app')
    op.drop_table('user', schema='file_app')
    # ### end Alembic commands ###
